name: localbox

services:
    nginx:
        image: nginx:alpine
        ports:
            - "${DOCKER_HOST_PORT:-8000}:80"
        volumes:
            - "./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro"
            - "./:/var/www/localbox"
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        environment:
            - "DATABASE_URL=mysql://root@mysql:3306/localbox?serverVersion=9.5"
        volumes:
            - "./docker/php/conf.d/default.ini:/usr/local/etc/php/conf.d/default.ini:ro"
            - "./storage:/var/www/storage"
            - "./:/var/www/localbox"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            mysql:
                condition: service_healthy

    mysql:
        image: mysql:9.5
        environment:
            - "MYSQL_DATABASE=localbox"
            - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            timeout: 5s
            retries: 10
