name: localbox

services:
    php:
        build:
            context: .
            dockerfile: ./docker/frankenphp/Dockerfile
            target: development
        ports:
            - "${DOCKER_HOST_PORT:-8000}:80"
        volumes:
            - "./docker/frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro"
            - "./docker/frankenphp/conf.d/php.development.ini:/usr/local/etc/php/conf.d/php.development.ini:ro"
            - "./docker/frankenphp/conf.d/xdebug.development.ini:/usr/local/etc/php/conf.d/zz-xdebug.ini:ro"
            - "./storage:/storage"
            - "./:/app"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        tty: true
